"""create_dndstats

Revision ID: 0000
Revises: 
Create Date: 2025-03-31 17:39:04.500299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0000'
down_revision = None
branch_labels = None
depends_on = None
add_models: dict[str, str] = {'dndstats': 'dnd_messaging_dndstatss'}
remove_models: dict[str, str] = {}
rename_models: dict[str, str] = {}


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dnd_messaging_dndstatss',
    sa.Column('user', sa.BigInteger(), nullable=False),
    sa.Column('charisma', sa.Integer(), nullable=False),
    sa.Column('intelligence', sa.Integer(), nullable=False),
    sa.Column('wisdom', sa.Integer(), nullable=False),
    sa.Column('deception', sa.Integer(), nullable=False),
    sa.Column('humor', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dnd_messaging_dndstatss')
    # ### end Alembic commands ###
