"""create_dndstatschannel

Revision ID: 0001
Revises: 0000
Create Date: 2025-03-31 18:03:38.751424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0001'
down_revision = '0000'
branch_labels = None
depends_on = None
add_models: dict[str, str] = {'dndstatschannel': 'dnd_messaging_dndstatschannels'}
remove_models: dict[str, str] = {}
rename_models: dict[str, str] = {}


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dnd_messaging_dndstatschannels',
    sa.Column('guild', sa.BigInteger(), nullable=False),
    sa.Column('channel', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('guild')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dnd_messaging_dndstatschannels')
    # ### end Alembic commands ###
