"""create_secretsantasession_create_secretsantamember

Revision ID: 0000
Revises: 
Create Date: 2023-11-28 21:21:08.205974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0000'
down_revision = None
branch_labels = None
depends_on = None
add_models: dict[str, str] = {'secretsantasession': 'secret_santa_secretsantasessions', 'secretsantamember': 'secret_santa_secretsantamembers'}
remove_models: dict[str, str] = {}
rename_models: dict[str, str] = {}


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('secret_santa_secretsantasessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('secret_santa_secretsantamembers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session', sa.Integer(), nullable=True),
    sa.Column('user', sa.BigInteger(), nullable=False),
    sa.Column('target', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['session'], ['secret_santa_secretsantasessions.id'], name='fk_secret_santa_secretsantamembers_secret_santa_secretsantasessions_id_session', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('secret_santa_secretsantamembers')
    op.drop_table('secret_santa_secretsantasessions')
    # ### end Alembic commands ###
