"""create_brand_create_gear_create_skill_create_gearrequest

Revision ID: 0000
Revises: 
Create Date: 2023-07-17 17:34:06.310723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0000'
down_revision = None
branch_labels = None
depends_on = None
add_models: dict[str, str] = {'brand': 'splatgear2_brands', 'skill': 'splatgear2_skills', 'gear': 'splatgear2_gears', 'gearrequest': 'splatgear2_gearrequests'}
remove_models: dict[str, str] = {}
rename_models: dict[str, str] = {}


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('splatgear2_brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('splatgear2_gears',
    sa.Column('_pid', sa.String(length=18), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('head', 'shoes', 'clothes', name='gearenum'), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('_pid')
    )
    op.create_table('splatgear2_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('splatgear2_gearrequests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.BigInteger(), nullable=False),
    sa.Column('gear_id', sa.String(length=18), nullable=True),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.Column('last_messaged', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['splatgear2_brands.id'], name='fk_splatgear2_gearrequests_splatgear2_brands_id_brand', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gear_id'], ['splatgear2_gears._pid'], name='fk_splatgear2_gearrequests_splatgear2_gears__pid_gear', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['splatgear2_skills.id'], name='fk_splatgear2_gearrequests_splatgear2_skills_id_skill', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('splatgear2_gearrequests')
    op.drop_table('splatgear2_skills')
    op.drop_table('splatgear2_gears')
    op.drop_table('splatgear2_brands')
    # ### end Alembic commands ###
