"""create_cyclones_create_noaazone_create_member_create_

Revision ID: 0000
Revises: 
Create Date: 2023-08-30 00:05:14.223679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0000'
down_revision = None
branch_labels = None
depends_on = None
add_models: dict[str, str] = {'noaazone': 'hurricane_noaazones', 'cyclones': 'hurricane_cycloness', 'member': 'hurricane_members'}
remove_models: dict[str, str] = {}
rename_models: dict[str, str] = {}


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hurricane_cycloness',
    sa.Column('pk', sa.String(length=30), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.Column('last_update', sa.DateTime(), nullable=False),
    sa.Column('next_update', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_table('hurricane_noaazones',
    sa.Column('id', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hurricane_members',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('ip', sa.String(length=15), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('noaa_zone', sa.String(length=8), nullable=True),
    sa.ForeignKeyConstraint(['noaa_zone'], ['hurricane_noaazones.id'], name='fk_hurricane_members_hurricane_noaazones_id_noaa_zone'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('members_cycloness',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cyclones', sa.String(length=30), nullable=True),
    sa.Column('member', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['cyclones'], ['hurricane_cycloness.pk'], name='fk_members_cycloness_hurricane_cycloness_cyclones_pk', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member'], ['hurricane_members.id'], name='fk_members_cycloness_hurricane_members_member_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('members_cycloness')
    op.drop_table('hurricane_members')
    op.drop_table('hurricane_noaazones')
    op.drop_table('hurricane_cycloness')
    # ### end Alembic commands ###
