"""create_cyclonechannel_modify_cyclonestype_modify_noaazoneexpires

Revision ID: 0001
Revises: 0000
Create Date: 2023-08-30 13:49:38.149935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0001'
down_revision = '0000'
branch_labels = None
depends_on = None
add_models: dict[str, str] = {'cyclonechannel': 'hurricane_cyclonechannels'}
remove_models: dict[str, str] = {}
rename_models: dict[str, str] = {}


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hurricane_cyclonechannels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('cyclone', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['cyclone'], ['hurricane_cycloness.pk'], name='fk_hurricane_cyclonechannels_hurricane_cycloness_pk_cyclone'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hurricane_cycloness', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=20), server_default='Tropical Depression', nullable=True))

    with op.batch_alter_table('hurricane_noaazones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expires', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hurricane_noaazones', schema=None) as batch_op:
        batch_op.drop_column('expires')

    with op.batch_alter_table('hurricane_cycloness', schema=None) as batch_op:
        batch_op.drop_column('type')

    op.drop_table('hurricane_cyclonechannels')
    # ### end Alembic commands ###
